version: 2.1
setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.1 # path-filteringに必要なorb

workflows:
  always-run: # pipeline parametersに関係なく実行するワークフロー
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          mapping: | # pipeline parametersをマッピング .circleci/continue_config.ymlに渡す
            app/views/.* run-test-views-job true
            app/controllers/.* run-test-controllers-job true
          base-revision: step8-path-filtering # 変更を検知するブランチ
          config-path: .circleci/continue_config.yml # 後続の処理定義ファイル
